datadir: /home/erigon/.local/share/erigon
chain: hermez-mainnet
http: true
private.api.addr: localhost:9091
zkevm.l2-chain-id: 1101
zkevm.l2-sequencer-rpc-url: https://zkevm-rpc.com
zkevm.l2-datastreamer-url: stream.zkevm-rpc.com:6900
zkevm.l1-chain-id: 1
zkevm.l1-rpc-url: http://anvil:8545

zkevm.address-sequencer: "0xA6215219d5d93dDe517F29af0e64079B2363C644"
zkevm.address-zkevm: "0x519E42c24163192Dca44CD3fBDCEBF6be9130987"
zkevm.address-rollup: "0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2"
zkevm.address-ger-manager: "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"

zkevm.default-gas-price: 1000000000
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.0375

zkevm.l1-rollup-id: 1
zkevm.l1-block-range: 20000
zkevm.l1-query-delay: 6000
zkevm.l1-first-block: 16896700
zkevm.datastream-version: 2

# debug.timers: true # Uncomment to enable timers

externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, zkevm]
http.addr: 0.0.0.0
http.vhosts: any
http.corsdomain: any
ws: true
zkevm.sequencer-block-seal-time: 3s
zkevm.sequencer-batch-seal-time: 15s
zkevm.sequencer-batch-verification-timeout: 30m
zkevm.sequencer-timeout-on-empty-tx-pool: 250ms
zkevm.executor-strict: false
zkevm.data-stream-host: 0.0.0.0
zkevm.data-stream-port: 6900
zkevm.sequencer-block-seal-time: 3s
zkevm.sequencer-batch-seal-time: 15s
zkevm.sequencer-batch-verification-timeout: 30m
zkevm.sequencer-timeout-on-empty-tx-pool: 250ms
zkevm.executor-strict: false
zkevm.data-stream-host: 0.0.0.0
zkevm.data-stream-port: 6900
